# Generated by Django 5.0.1 on 2024-06-16 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('cost_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_country', models.CharField(max_length=255)),
                ('destination_country', models.CharField(max_length=255)),
                ('cost_per_trip', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CostSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheets', to='core.country')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheets', to='crm.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='CostSheetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('margin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cost_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='costing.costsheet')),
                ('provider', models.ForeignKey(blank=True, limit_choices_to={'is_provider': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='GenericExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_expenses', to='costing.costsheet')),
            ],
        ),
        migrations.CreateModel(
            name='PercentageExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expense_type', models.CharField(choices=[('total_cost_sheet', 'Total Cost Sheet'), ('total_price', 'Total Price'), ('total_cost', 'Total Cost'), ('total_profit', 'Total Profit')], max_length=50)),
                ('cost_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percentage_expenses', to='costing.costsheet')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField()),
                ('cost_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='costing.costsheet')),
                ('daily_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costing.dailyexpense')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costing.flight')),
            ],
        ),
    ]
